classDiagram
    class Book{
        +String title
        +String author
        +String isbn
        +boolean isAvailable
        +User borrowedBy
        +List<User> reservationList
    }
    class User{
    }
    class Library{
    }
    class Librarian{
    }
