---
title: Library Management System Class Diagram
---
classDiagram
    User "1" --> "1" Library : submits request to
    Library "1" o-- "*" Book : has
    Library "1" *-- "1" Librarian : employs
    Librarian "1" --> "*" Book : manages
    Book "1" --> "0..1" User : reserved by
    Book "1" --> "0..*" User : waitlisted by

    class Book{
        +str title
        +str author
        +str isbn
        -bool _is_available
        -User _current_borrower
        -List<User> _waitlist
        +get_availability(): bool
        +get_current_borrower(): User
        +get_waitlist(): List<User>
        +borrow(user: User): void
        +return_book(user: User): void
        +add_to_waitlist(user: User): void
        +remove_from_waitlist(user: User): void
    }
    class User{
        +str name
        +List<Book> borrowed_books
        +borrow_book(library: Library, title: str): void
        +return_book(library: Library, title: str): void
        +add_borrowed_book(book: Book): void
        +removed_borrowed_book(book: Book): void
    }
    class Librarian{
        +manage_return(book: Book, user: User): void
        +manage_waitlist(book: Book, user: User): void
    }
    class Library{
        +List<Book> books
        +List<User> users
        +Librarian librarian
        +add_user(user: User): void
        +add_book(book: Book): void
        +borrow_book(book: Book, user: User): void
        +return_book(book: Book, user: User): void
    }
