---
title: Book State Diagram
---
stateDiagram
    [*] --> Available
    Available --> Borrowed : Borrow Request [isAvailable == true]
    Available --> Waitlisted : Borrow [isAvailable == false]
    Borrowed --> Waitlisted : Borrow [isAvailable == false]
    Waitlisted --> Waitlisted : Borrow [isAvailable == false]
    Borrowed --> Available : Return [waitList.isEmpty() == true]
    Borrowed --> Borrowed : Return [waitList.isEmpty() == false]
    Waitlisted --> Borrowed : Return [waitList.size() == 1]
    Waitlisted --> Waitlisted : Return [waitList.size() > 0]
