---
title: Book State Diagram
---
stateDiagram
    [*] --> Available

    Available --> Borrowed : Borrow Request [isAvailable == true]

    %% Add first user to waitlist queue
    Available --> Waitlisted : Borrow [isAvailable == false]

    %% Borrow request made, but book is already borrowed, add (or allocate) user to waitlist queue
    Borrowed --> Waitlisted : Borrow [isAvailable == false]

    %% Borrow request made, but book is already borrowed & there exists a waitlist queue already, so append to that
    Waitlisted --> Waitlisted : Borrow [isAvailable == false]

    %% Make the book available for borrowing
    Borrowed --> Available : Return [waitList.isEmpty() == true]

    %% Give the book to the next user in the waitlist queue
    Borrowed --> Borrowed : Return [waitList.isEmpty() == false]

    %% Remove from waitlisted after last user in queue leaves
    Waitlisted --> Borrowed : Return [waitList.size() == 1]

    %% Remove the first user in the waitlist queue
    Waitlisted --> Waitlisted : Return [waitList.size() > 0]
